name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deply_lambda:
    runs-on: ubuntu-latest  # Specify the runner environment here

    steps:  # Steps should be on the same level as runs-on
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

    
